version: '3.9'
services:
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './application:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
            - './application/public:/usr/share/nginx/html'
        ports:
            - '42000:80'

    php-fpm:
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - './application:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
